behaviors:
  EliminationAgentSac:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0003
      learning_rate_schedule: constant
      batch_size: 64
      buffer_size: 50000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 600000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 10000
      team_change: 50000
      swap_steps: 10000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0