behaviors:
  EliminationAgentBasic:
    trainer_type: ppo
    hyperparameters:
      batch_size: 204
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 600000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
    self_play:
      save_steps: 10000
      team_change: 50000
      swap_steps: 10000
      window: 5
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0